Add new documentation for Arch Linux user.
marktext/marktext pull request #3619
Opened 2023-05-01 18:33 UTC by sukalaper

| Q                 | A
| ----------------- | ---
| New tests added?  | yes
| Add documentation | yes
| Fixed tickets     | Fixes #ticket number (set to none if no tickets are fixed, repeat template for each ticket fixed)
| License           | MIT

### Description
Hello, sorry for my contribution which may still be very messy.

When I did the installation on Arch Linux, it required `electron15-bin` and `ripgrep` which is not available by default, here I only add documentation for users who have problems like me.

2023-05-07 18:47 UTC, Teloshav requested changes
Is the line "`electron15-bin`, and `ripgrep`" meant to have the comma and the 'and'?

E.g. "`electron15-bin`, and `ripgrep`" vs. `electron15-bin` and `ripgrep`.

2023-05-07 19:05 UTC, sukalaper commented
> Is the line "`electron15-bin`, and `ripgrep`" meant to have the comma and the 'and'?
> 
> E.g. "`electron15-bin`, and `ripgrep`" vs. `electron15-bin` and `ripgrep`.

thanks for the correction, sorry it was my mistake.

2023-05-07 19:44 UTC, Teloshav approved these changes
Looks good to me. :+1:

2023-09-27 13:51 UTC, alerque requested changes
This should not be merged, some parts are factually wrong and the other part is confusing. The `ripgrep` package is not in the AUR, it is in the `[extra]` repository. As are half a dozen other dependencies that will be installed by default. It is not necessary to document these since AUR packages *always* have their dependencies called out in the package meta data and pacman will automatically resolve them. The Electron one is a bit trickier since the `electron15` package got dropped from `[extra]`, but the AUR package `electron15-bin` does `provide=(electron15)`, which means pacman and many AUR helpers can and do resolve it as supplying the needed dependency for Marktext. These should *not* be documented in this README as they are subject to change and are standard Arch/AUR usage. If anything the one thing that could be documented is that I (as the AUR package maintainer and official Arch Linux Package Maintainer) host a repository (signed with official Arch Linux keys) that has both the Electron dependency and this package prebuilt so it can be installed with to compiling necessary. That might be useful to mention, how to use the AUR is out of scope.

2023-09-27 15:39 UTC, closed without merging